services:
  db:
    image: mariadb:latest
    container_name: gitpod-wpdev-db
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: ./.env/wp-dockerfile #contains WP-CLI
    container_name: gitpod-wpdev-wordpress
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - ./wp-core:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./.env/wp-apache-logs:/var/log/apache2
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./.env/pma-apache-logs:/var/log/apache2
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
      
volumes:
  db-data:
  wp-apache-logs:
  pma-apache-logs: